### ISSUE TITLE
Infografia de Librerias

### ISSUE THREAD

**Issue by carlos-chrs** [SistemasTecTlaxiaco/infografia-de-las-librerias-carlos-chrs#2]
[Infografia-librerias..pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-carlos-chrs/files/6359220/Infografia-librerias.pdf)

**Comment by Edwin38H** [comment]
cal. 20
muy detallado en informacion

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
